[workspace]
members = [
    "db_struct_mapper",
    "db_struct_mapper_derive",
    "db_struct_mapper_internal",
]
resolver = "2"
[workspace.dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = {version = "2.0.*", features = ["full", "extra-traits"] }
